### ISSUE TITLE
How to properly shutdown the ChangeFeedHost

### ISSUE THREAD

**Issue by chetanmeh** [Azure/azure-documentdb-changefeedprocessor-java#63]
What would be the right way to shutdown the host along with its observer. There was some code added #47 but I see that was later reverted.

Should we just terminate the executor service or is there a way to do proper shutdown such that leases can be removed?

**Comment by chetanmeh** [comment]
In our case we do close the `ExecutorService` attached with `ChangeFeedEventHost` but still see error logs upon close like

```
[2019-06-07T06:51:03.639Z] [ERROR] Other exception not handled happened: null 
java.lang.NullPointerException
	at com.microsoft.azure.documentdb.changefeedprocessor.services.CheckpointServices.getCheckpoint(CheckpointServices.java:77)
	at com.microsoft.azure.documentdb.changefeedprocessor.services.CheckpointServices.getCheckpointData(CheckpointServices.java:49)
	at com.microsoft.azure.documentdb.changefeedprocessor.services.ChangeFeedJob.QueryChangeFeed(ChangeFeedJob.java:159)
	at com.microsoft.azure.documentdb.changefeedprocessor.services.ChangeFeedJob.lambda$start$0(ChangeFeedJob.java:136)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

Seems like each `ChangeFeedJob` has its own `ExecutorService` instance and there is no direct way to trigger its close as `partitionManager` instance is not exposed from the `ChangeFeedEventHost`
